"""init

Revision ID: 85c6cd869563
Revises: 4e1e498a0634
Create Date: 2023-10-28 12:58:02.150882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c6cd869563'
down_revision = '4e1e498a0634'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
