"""init

Revision ID: 4e1e498a0634
Revises: 2b2902d3853c
Create Date: 2023-10-28 12:57:34.357771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1e498a0634'
down_revision = '2b2902d3853c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
