"""init

Revision ID: 62522b36a033
Revises: 85c6cd869563
Create Date: 2023-10-28 12:58:20.852450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62522b36a033'
down_revision = '85c6cd869563'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
